name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: download protoc
        run: sudo apt-get install -y protobuf-compiler
      - name: Show cargo version
        run: cargo --version
      - name: Fetch
        run: |
          cargo fetch --locked
      - name: Build
        run: |
          cargo build --release --frozen
      - name: Test
        run: |
          cargo test --release --frozen --workspace
